---
    - hosts: all
      become: yes
      tasks:
      # For demo purposes, this takes too long lol
      # - name: Update package list and cache
      #   apt:
      #     name: "*"
      #     state: latest  
      #     update_cache: yes

      - name: Make sure nginx is installed
        apt:
          name: nginx
          state: latest

      - name: start nginx
        service:
            name: nginx
            state: started

      - name: copy the nginx config file and restart nginx
        copy:
          src: ./ngnix.cfg
          dest: /etc/nginx/sites-available/static_site.cfg

      - name: create symlink
        file:
          src: /etc/nginx/sites-available/static_site.cfg
          dest: /etc/nginx/sites-enabled/default
          state: link
        become: yes

      - name: copy the content of the web site
        copy:
          src: ./static-site-src/
          dest: /home/ubuntu/static-site

      - name: restart nginx
        service:
          name: nginx
          state: restarted
  